<?php

/**
 * <i>CTerm</i> class definition.
 *
 * This file contains the class definition of <b>CTerm</b> which represents the ancestor of
 * all term classes.
 *
 *	@package	MyWrapper
 *	@subpackage	Framework
 *
 *	@author		Milko A. Škofič <m.skofic@cgiar.org>
 *	@version	1.00 05/09/2012
 */

/*=======================================================================================
 *																						*
 *										CTerm.php										*
 *																						*
 *======================================================================================*/

/**
 * Tokens.
 *
 * This include file contains all default token definitions.
 */
require_once( kPATH_MYWRAPPER_LIBRARY_DEFINE."/Tokens.inc.php" );

/**
 * Category trait.
 *
 * This includes the category trait definitions.
 */
require_once( kPATH_MYWRAPPER_LIBRARY_CLASS."/TCategory.php" );

/**
 * Ancestor.
 *
 * This includes the ancestor class definitions.
 */
require_once( kPATH_MYWRAPPER_LIBRARY_CLASS."/CPersistentObject.php" );

/**
 * <h4>Term object ancestor</h4>
 *
 * A term is an object that features the following default properties:
 *
 * <ul>
 *	<li><i>Local identifier</i>: The local identifier, <tt>{@link LID()}</tt> or the
 *		<tt>{@link kTAG_LID}</tt> tag, is a string code that uniquely identifies the object
 *		among all those sharing the same namespace. This attribute is required.
 *	<li><i>Global identifier</i>: The global identifier, <tt>{@link GID()}</tt> or the
 *		<tt>{@link kTAG_GID}</tt> tag, is a string code that uniquely identifies the object
 *		among all other objects, regardless of their namespace. This attribute is required
 *		and will be generated.
 *	<li><i>Namespace</i>: The namespace, <tt>{@link NS()}</tt> or the
 *		<tt>{@link kTAG_NAMESPACE}</tt> tag, is a container for a set of term local
 *		identifiers allowing disambiguation or homonym local term identifiers. The current
 *		term global identifier is generated by concatenating the namespace global identifier
 *		to the term's local identifier separated by the {@link kTOKEN_NAMESPACE_SEPARATOR}
 *		token. This attribute is optional.
 *	<li><i>Label</i>: The label or name, <tt>{@link Label()}</tt> or the
 *		<tt>{@link kTAG_LABEL}</tt> tag, represents the label, name or short description of
 *		the term. This attribute is constituted by an array of elements in which the value
 *		of the element represents the label string and the element key is the language code
 *		in which the label is expressed in. This attribute is optional.
 *	<li><i>Definition</i>: The definition, <tt>{@link Definition()}</tt> or the
 *		<tt>{@link kTAG_DEFINITION}</tt> tag, represents the definition or long label of the
 *		term. This attribute is constituted by an array of elements in which the value of
 *		the element represents the definition string and the element key is the language
 *		code in which the definition is expressed in. This attribute is optional.
 *	<li><i>Synonyms</i>: The synonym or alias, <tt>{@link Synonym()}</tt> or
 *		the <tt>{@link kTAG_SYNONYMS}</tt> tag, represents a list of strings that represent
 *		alternative names or identifiers for the term. These strings are comparable to
 *		variable names and do not have a language scope. This attribute is optional.
 *	<li><i>Master</i>: The master, <tt>{@link Master()}</tt> or the
 *		<tt>{@link kTAG_MASTER}</tt> tag, is a reference to another term that hosts the
 *		attributes of the current term. This can be used to redirect synonymous terms to a
 *		single instance that holds all the attributes common to the referencing terms. This
 *		is used to prevent duplicating attributes for synonym terms. This attribute is
 *		constituted by the {@link kTAG_NID} of the referenced term and is optional.
 * </ul>
 *
 * The native identifier of the term, {@link kTAG_NID}, is equivalent to the global
 * identifier, in derived classes the native identifier will generally be a hash of the
 * global identifier.
 *
 * Once the object has been committed, besides the global and native identifiers, also the
 * {@link kTAG_NAMESPACE} and {@link kTAG_LID} attributes will be locked, since they are
 * used to generate the unique identifier.
 *
 * The object will have its {@link _IsInited()} status set if the local identifier,
 * {@link kTAG_LID}, is set.
 *
 *	@package	MyWrapper
 *	@subpackage	Framework
 */
class CTerm extends CPersistentObject
{
		

/*=======================================================================================
 *																						*
 *											TRAITS										*
 *																						*
 *======================================================================================*/


	 
	/*===================================================================================
	 *	TCategory																		*
	 *==================================================================================*/

	/**
	 * <h4>Category traits</h4>
	 *
	 * This trait provides accessor methods for the category properties of the object:
	 *
	 * <ul>
	 *	<li><tt>{@link Category()}</tt>: The <i>categories</i>, {@link kTAG_CATEGORY},
	 *		represent a set of values that constitute the category of the hosting object.
	 *	<li><tt>{@link Kind()}</tt>: The <i>kinds</i>, {@link kTAG_KIND}, represent a set of
	 *		enumerations that represent the kind of of the hosting object.
	 *	<li><tt>{@link Type()}</tt>: The <i>types</i>, {@link kTAG_TYPE}, represent a set of
	 *		enumerations that represent the type of of the hosting object.
	 * </ul>
	 */
	use TCategory;
		

/*=======================================================================================
 *																						*
 *								PUBLIC MEMBER INTERFACE									*
 *																						*
 *======================================================================================*/


	 
	/*===================================================================================
	 *	NS																				*
	 *==================================================================================*/

	/**
	 * <h4>Manage namespace</h4>
	 *
	 * The <i>namespace</i>, {@link kTAG_NAMESPACE}, holds the prefix of the current term's
	 * global identifier, {@link kTAG_GID}: the latter is constituted by concatenating the
	 * namespace with the local identifier, {@link kTAG_LID}, separated by a
	 * {@link kTOKEN_NAMESPACE_SEPARATOR} token.
	 *
	 * The namespace acts as a container for a set of term local identifiers, allowing for
 	 * homonym local term identifiers.
	 *
	 * The method accepts a parameter which represents either the namespace or the
	 * requested operation, depending on its value:
	 *
	 * <ul>
	 *	<li><tt>NULL</tt>: Return the current value.
	 *	<li><tt>FALSE</tt>: Delete the current value.
	 *	<li><i>other</i>: Set the value with the provided parameter.
	 * </ul>
	 *
	 * The second parameter is a boolean which if <tt>TRUE</tt> will return the <i>old</i>
	 * value when replacing containers; if <tt>FALSE</tt>, it will return the currently set
	 * value.
	 *
	 * Note that when the object has the {@link _IsCommitted()} status this offset will be
	 * locked and an exception will be raised.
	 *
	 * @param mixed					$theValue			Native identifier or operation.
	 * @param boolean				$getOld				<tt>TRUE</tt> get old value.
	 *
	 * @access public
	 * @return mixed				<i>New</i> or <i>old</i> native container.
	 *
	 * @uses ManageOffset()
	 *
	 * @see kTAG_NAMESPACE
	 */
	public function NS( $theValue = NULL, $getOld = FALSE )
	{
		return ManageOffset( $this, kTAG_NAMESPACE, $theValue, $getOld );			// ==>

	} // NS.

	 
	/*===================================================================================
	 *	LID																				*
	 *==================================================================================*/

	/**
	 * <h4>Manage local unique identifier</h4>
	 *
	 * The <i>local unique identifier</i>, {@link kTAG_LID}, holds a string which
	 * represents the object's unique identifier within its namespace, this value is
	 * concatenated to the eventual's namespace's global identifier to form the term's
	 * global identifier. 
	 *
	 * The method accepts a parameter which represents either the identifier or the
	 * requested operation, depending on its value:
	 *
	 * <ul>
	 *	<li><tt>NULL</tt>: Return the current value.
	 *	<li><tt>FALSE</tt>: Delete the current value.
	 *	<li><i>other</i>: Set the value with the provided parameter.
	 * </ul>
	 *
	 * The second parameter is a boolean which if <tt>TRUE</tt> will return the <i>old</i>
	 * value when replacing containers; if <tt>FALSE</tt>, it will return the currently set
	 * value.
	 *
	 * Note that when the object has the {@link _IsCommitted()} status this offset will be
	 * locked and an exception will be raised.
	 *
	 * @param mixed					$theValue			Native identifier or operation.
	 * @param boolean				$getOld				<tt>TRUE</tt> get old value.
	 *
	 * @access public
	 * @return mixed				<i>New</i> or <i>old</i> native container.
	 *
	 * @uses ManageOffset()
	 *
	 * @see kTAG_LID
	 */
	public function LID( $theValue = NULL, $getOld = FALSE )
	{
		return ManageOffset( $this, kTAG_LID, $theValue, $getOld );					// ==>

	} // LID.

	 
	/*===================================================================================
	 *	Master																			*
	 *==================================================================================*/

	/**
	 * <h4>Manage term reference</h4>
	 *
	 * This method can be used to manage the term reference, {@link kTAG_MASTER}, which
	 * represents the term that hosts all the attributes for the current term.
	 *
	 * This attribute is used when defining exact term synonyms: instead of duplicating the
	 * attributes in all the synonyms, one can store them in one term and have all the other
	 * synonyms point to that term, that way storage and changes reside in a single place.
	 *
	 * The method accepts a parameter which represents either the term, or the requested
	 * operation, depending on its value:
	 *
	 * <ul>
	 *	<li><tt>NULL</tt>: Return the current value.
	 *	<li><tt>FALSE</tt>: Delete the current value.
	 *	<li><i>other</i>: Set the value with the provided parameter.
	 * </ul>
	 *
	 * The second parameter is a boolean which if <tt>TRUE</tt> will return the <i>old</i>
	 * value when replacing containers; if <tt>FALSE</tt>, it will return the currently set
	 * value.
	 *
	 * @param mixed					$theValue			Term or operation.
	 * @param boolean				$getOld				<tt>TRUE</tt> get old value.
	 *
	 * @access public
	 * @return mixed				<i>New</i> or <i>old</i> native container.
	 *
	 * @uses ManageOffset()
	 *
	 * @see kTAG_MASTER
	 */
	public function Master( $theValue = NULL, $getOld = FALSE )
	{
		return ManageOffset( $this, kTAG_MASTER, $theValue, $getOld );				// ==>

	} // Master.

	 
	/*===================================================================================
	 *	Label																			*
	 *==================================================================================*/

	/**
	 * <h4>Manage term label</h4>
	 *
	 * The term <i>label</i>, {@link kTAG_LABEL}, represents the term's name or short
	 * human readable description. It is an optional attribute of the object that holds
	 * an array of elements in which the index is represented by the language code and the
	 * value is the string.
	 *
	 * No two elements may share the same language code.
	 *
	 * The method accepts the following parameters:
	 *
	 * <ul>
	 *	<li><tt>$theLanguage</tt>: Language code.
	 *	<li><tt>$theValue</tt>: The label string or the operation, depending on its value:
	 *	 <ul>
	 *		<li><tt>NULL</tt>: Return the string corresponding to the provided language.
	 *		<li><tt>FALSE</tt>: Delete the element corresponding to the provided language.
	 *		<li><i>other</i>: Any other value represents the label string that will be set
	 *			or replace the entry for the provided language.
	 *	 </ul>
	 *	<li><tt>$getOld</tt>: If <tt>TRUE</tt>, the method will return the label
	 *		<i>before</i> it was eventually modified; if <tt>FALSE</tt>, the method will
	 *		return the value <i>after</i> eventual modifications.
	 * </ul>
	 *
	 * @param mixed					$theLanguage		Language code.
	 * @param mixed					$theValue			Label or operation.
	 * @param boolean				$getOld				<tt>TRUE</tt> get old value.
	 *
	 * @access public
	 * @return mixed				<i>New</i> or <i>old</i> label.
	 *
	 * @uses ManageIndexedOffset()
	 *
	 * @see kTAG_LABEL
	 */
	public function Label( $theLanguage = NULL, $theValue = NULL, $getOld = FALSE )
	{
		return ManageIndexedOffset
				( $this, kTAG_LABEL, $theLanguage, $theValue, $getOld );			// ==>

	} // Label.

	 
	/*===================================================================================
	 *	Definition																		*
	 *==================================================================================*/

	/**
	 * <h4>Manage term definition</h4>
	 *
	 * The term <i>definition</i>, {@link kTAG_DEFINITION}, represents the term's
	 * definition, or its description unrelated to the context. It is an optional attribute
	 * of the object that holds an array of elements in which the index is represented by
	 * the language code and the value is the string.
	 *
	 * No two elements may share the same language code.
	 *
	 * The definition does not depend on the context in which the object is, as opposed to
	 * the description which depends on the context.
	 *
	 * The method accepts the following parameters:
	 *
	 * <ul>
	 *	<li><tt>$theLanguage</tt>: Language code.
	 *	<li><tt>$theValue</tt>: The definition string or the operation, depending on its
	 *		value:
	 *	 <ul>
	 *		<li><tt>NULL</tt>: Return the string corresponding to the provided language.
	 *		<li><tt>FALSE</tt>: Delete the element corresponding to the provided language.
	 *		<li><i>other</i>: Any other value represents the definition string that will set
	 *			or replace the entry for the provided language.
	 *	 </ul>
	 *	<li><tt>$getOld</tt>: If <tt>TRUE</tt>, the method will return the definition
	 *		string <i>before</i> it was eventually modified; if <tt>FALSE</tt>, the method
	 *		will return the value <i>after</i> eventual modifications.
	 * </ul>
	 *
	 * @param mixed					$theLanguage		Language code.
	 * @param mixed					$theValue			Definition or operation.
	 * @param boolean				$getOld				<tt>TRUE</tt> get old value.
	 *
	 * @access public
	 * @return mixed				<i>New</i> or <i>old</i> definition.
	 *
	 * @uses ManageIndexedOffset()
	 *
	 * @see kTAG_DEFINITION
	 */
	public function Definition( $theLanguage = NULL, $theValue = NULL, $getOld = FALSE )
	{
		return ManageIndexedOffset
				( $this, kTAG_DEFINITION, $theLanguage, $theValue, $getOld );		// ==>

	} // Definition.

	 
	/*===================================================================================
	 *	Synonym																			*
	 *==================================================================================*/

	/**
	 * <h4>Manage term synonyms</h4>
	 *
	 * This method can be used to manage the term's synonyms, {@link kTAG_SYNONYMS},
	 * which contains a list of strings that represent alternate codes or names that can be
	 * used to identify the term.
	 *
	 * This offset collects the list of synonyms in an enumerated set that can be managed
	 * with the following parameters:
	 *
	 * <ul>
	 *	<li><tt>$theValue</tt>: Depending on the next parameter, this may either refer to
	 *		the value to be set or to the index of the element to be retrieved or deleted:
	 *	 <ul>
	 *		<li><tt>NULL</tt>: This value indicates that we want to operate on all elements,
	 *			which means, in practical terms, that we either want to retrieve or delete
	 *			the full list. If the operation parameter resolves to <tt>TRUE</tt>, the
	 *			method will default to retrieving the current list and no new element will
	 *			be added.
	 *		<li><tt>array</tt>: An array indicates that we want to operate on a list of
	 *			values and that other parameters may also be provided as lists. Note that
	 *			{@link ArrayObject} instances are not considered here as arrays.
	 *		<li><i>other</i>: Any other type represents either the new value to be added or
	 *			the index to the value to be returned or deleted.
	 *	 </ul>
	 *	<li><tt>$theOperation</tt>: This parameter represents the operation to be performed
	 *		whose scope depends on the value of the previous parameter:
	 *	 <ul>
	 *		<li><tt>NULL</tt>: Return the element or full list.
	 *		<li><tt>FALSE</tt>: Delete the element or full list.
	 *		<li><tt>array</tt>: This type is only considered if the <tt>$theValue</tt>
	 *			parameter is provided as an array: the method will be called for each
	 *			element of the <tt>$theValue</tt> parameter matched with the corresponding
	 *			element of this parameter, which also means that both both parameters must
	 *			share the same count.
	 *		<li><i>other</i>: Add the <tt>$theValue</tt> value to the list. If you provided
	 *			<tt>NULL</tt> in the previous parameter, the operation will be reset to
	 *			<tt>NULL</tt>.
	 *	 </ul>
	 *	<li><tt>$getOld</tt>: Determines what the method will return:
	 *	 <ul>
	 *		<li><tt>TRUE</tt>: Return the value <i>before</i> it was eventually modified.
	 *		<li><tt>FALSE</tt>: Return the value <i>after</i> it was eventually modified.
	 *	 </ul>
	 * </ul>
	 *
	 * @param mixed					$theValue			Value or index.
	 * @param mixed					$theOperation		Operation.
	 * @param boolean				$getOld				TRUE get old value.
	 *
	 * @access public
	 * @return mixed				<i>New</i> or <i>old</i> type.
	 *
	 * @uses ManageObjectSetOffset()
	 *
	 * @see kTAG_SYNONYMS
	 */
	public function Synonym( $theValue = NULL, $theOperation = NULL, $getOld = FALSE )
	{
		return ManageObjectSetOffset
			( $this, kTAG_SYNONYMS, $theValue, $theOperation, $getOld );			// ==>

	} // Synonym.
		


/*=======================================================================================
 *																						*
 *							STATIC IDENTIFICATION INTERFACE								*
 *																						*
 *======================================================================================*/


	 
	/*===================================================================================
	 *	TermCode																		*
	 *==================================================================================*/

	/**
	 * <h4>Return the term global unique identifier</h4>
	 *
	 * This static method should be used to compile the term's global identifier, it expects
	 * the optional namespace global identifier and the term local identifier, the method
	 * will generate the term's global identifier.
	 *
	 * @param string				$theIdentifier		Term local identifier.
	 * @param string				$theNamespace		Namespace global identifier.
	 *
	 * @static
	 * @return string				The term's global unique identifier.
	 *
	 * @see kTAG_GID kTAG_NAMESPACE kTOKEN_NAMESPACE_SEPARATOR
	 */
	static function TermCode( $theIdentifier, $theNamespace = NULL )
	{
		//
		// Init identifier.
		//
		return ( $theNamespace === NULL )
			 ? $theIdentifier
			 : ( (string) $theNamespace
			    .kTOKEN_NAMESPACE_SEPARATOR
			    . (string) $theIdentifier );										// ==>
	
	} // TermCode.
		


/*=======================================================================================
 *																						*
 *							PROTECTED IDENTIFICATION INTERFACE							*
 *																						*
 *======================================================================================*/


	 
	/*===================================================================================
	 *	_index																			*
	 *==================================================================================*/

	/**
	 * <h4>Return the object's global unique identifier</h4>
	 *
	 * Term identifiers are constituted by the concatenation of the namespace and the local
	 * unique identifier of the current term separated by a
	 * {@link kTOKEN_NAMESPACE_SEPARATOR} token, this code is generated by the static
	 * {@link TermCode()} method.
	 *
	 * If the term lacks a namespace, its local identifier will become its global
	 * identifier.
	 *
	 * Both the namespace and the local identifier will be converted to strings to compute
	 * the global identifier.
	 *
	 * @param CConnection			$theConnection		Server, database or container.
	 * @param bitfield				$theModifiers		Commit options.
	 *
	 * @access protected
	 * @return string|NULL			The object's global unique identifier.
	 *
	 * @see kTAG_LID kTAG_NAMESPACE kTOKEN_NAMESPACE_SEPARATOR
	 */
	protected function _index( CConnection $theConnection, $theModifiers )
	{
		//
		// Get term local identifier.
		//
		if( $this->offsetExists( kTAG_LID ) )
			return static::TermCode( $this->offsetGet( kTAG_LID ),
									 ( $this->offsetExists( kTAG_NAMESPACE ) )
									 ? $this->offsetGet( kTAG_NAMESPACE )
									 : NULL );										// ==>
		
		return parent::_index( $theContainer, $theModifiers );						// ==>
	
	} // _index.
		


/*=======================================================================================
 *																						*
 *								PROTECTED OFFSET INTERFACE								*
 *																						*
 *======================================================================================*/


	 
	/*===================================================================================
	 *	_Preset																			*
	 *==================================================================================*/

	/**
	 * <h4>Handle offset before setting it</h4>
	 *
	 * In this class we prevent the modification of offsets that concur in the generation of
	 * the object's identifier if the object has its {@link _IsCommitted()} status set. This
	 * is because referenced objects must not change identifier.
	 *
	 * The {@link kTAG_NAMESPACE} and {@link kTAG_LID} are locked if the object was
	 * committed, {@link _IsCommitted()}.
	 *
	 * @param reference			   &$theOffset			Offset.
	 * @param reference			   &$theValue			Value to set at offset.
	 *
	 * @access protected
	 *
	 * @throws Exception
	 *
	 * @uses _IsCommitted()
	 *
	 * @see kTAG_NAMESPACE kTAG_LID
	 */
	protected function _Preset( &$theOffset, &$theValue )
	{
		//
		// Intercept namespace and local identifier.
		//
		$offsets = array( kTAG_NAMESPACE, kTAG_LID );
		if( $this->_IsCommitted()
		 && in_array( $theOffset, $offsets ) )
			throw new Exception
				( "You cannot modify the [$theOffset] offset: "
				 ."the object is committed",
				  kERROR_LOCKED );												// !@! ==>
		
		//
		// Check label and definition types.
		//
		$offsets = array( kTAG_LABEL, kTAG_DEFINITION );
		if( in_array( $theOffset, $offsets )
		 && ($theValue !== NULL)
		 && (! is_array( $theValue )) )
			throw new Exception
				( "You cannot set the [$theOffset] offset: "
				 ."invalid value, expecting an array",
				  kERROR_PARAMETER );											// !@! ==>
		
		//
		// Call parent method.
		//
		parent::_Preset( $theOffset, $theValue );
	
	} // _Preset.

	 
	/*===================================================================================
	 *	_Preunset																		*
	 *==================================================================================*/

	/**
	 * <h4>Handle offset before unsetting it</h4>
	 *
	 * In this class we prevent the modification of offsets that concur in the generation of
	 * the object's identifier if the object has its {@link _IsCommitted()} status set. This
	 * is because referenced objects must not change identifier.
	 *
	 * The {@link kTAG_NAMESPACE} and {@link kTAG_LID} are locked if the object was
	 * committed, {@link _IsCommitted()}.
	 *
	 * @param reference			   &$theOffset			Offset.
	 *
	 * @access protected
	 *
	 * @throws Exception
	 *
	 * @uses _IsCommitted()
	 *
	 * @see kTAG_NAMESPACE kTAG_LID
	 */
	protected function _Preunset( &$theOffset )
	{
		//
		// Intercept namespace and local identifier.
		//
		$offsets = array( kTAG_NAMESPACE, kTAG_LID );
		if( $this->_IsCommitted()
		 && in_array( $theOffset, $offsets ) )
			throw new Exception
				( "You cannot modify the [$theOffset] offset: "
				 ."the object is committed",
				  kERROR_LOCKED );												// !@! ==>
		
		//
		// Call parent method.
		//
		parent::_Preunset( $theOffset );
	
	} // _Preunset.
		


/*=======================================================================================
 *																						*
 *								PROTECTED STATUS INTERFACE								*
 *																						*
 *======================================================================================*/


	 
	/*===================================================================================
	 *	_Ready																			*
	 *==================================================================================*/

	/**
	 * <h4>Determine if the object is ready</h4>
	 *
	 * In this class we tie the {@link _IsInited()} status to the presence or absence of the
	 * {@link kTAG_LID} offset.
	 *
	 * @access protected
	 * @return boolean				<tt>TRUE</tt> means {@link _IsInited( <tt>TRUE</tt> ).
	 *
	 * @uses _Ready()
	 *
	 * @see kTAG_LID
	 */
	protected function _Ready()
	{
		//
		// Check parent.
		//
		if( parent::_Ready() )
			return $this->offsetExists( kTAG_LID );									// ==>
		
		return FALSE;																// ==>
	
	} // _Ready.

	 

} // class CTerm.


?>
